### PR TITLE
A clean slider instead of buttons

### PR DESCRIPTION
**Pull request by MEEPofFaith**
Wow that shortened main.js by a lot.

https://user-images.githubusercontent.com/54301439/166622467-e078e959-8170-4cb5-ac74-69421fa185b9.mp4

### CODE REVIEW

**Comment by sk7725** [comment]
I'll look into this tonight, but i really want the old UI to stay as an option...

Still great job :+1:

**Comment by MEEPofFaith** [comment]
> I'll look into this tonight, but i really want the old UI to stay as an option...

~~yea have fun fitting in the old bloated code~~

**Comment by sk7725** [comment]
is this okay to merge? ~~why not make quicktapping reset many times unlock devmode where the scroll goes up to x1024~~

**Comment by MEEPofFaith** [comment]
yea I don't have any more ideas so sure

**Pull request merged**
