### PR TITLE
Fix TC on Erekir (Mobile)

### PR DESCRIPTION
**Pull request by MEEPofFaith**
image

### CODE REVIEW

**Comment by sk7725** [comment]
can you drop the tex background and use a transparent black? i think the edges (padding) are bloating

**Comment by MEEPofFaith** [comment]
?

**Comment by sk7725** [comment]
Tex.buttonEdge3 to something without the annoying edges, like the unit control button

**Comment by MEEPofFaith** [comment]
Like this?
image

**Pull request merged**
